export const ROOT = '/'
export const DASHBOARDS_PREFIX_PATH = '/dashboards'
export const CONCEPTS_PREFIX_PATH = '/concepts'
export const AUTH_PREFIX_PATH = '/auth'
export const UI_COMPONENTS_PREFIX_PATH = '/ui-components'
export const PAGES_PREFIX_PATH = '/pages'
export const GUIDE_PREFIX_PATH = '/guide'
export const SALES_PREFIX_PATH = '/SalesDetails'
export const USER_PREFIX_PATH = '/UserModule'
export const USER_MENU_PREFIX_PATH = '/User-menu'
export const SALES_MENU_PREFIX_PATH = '/Sales-menu'
export const USER_MENU_MODIFIY_USER = '/User-menu-ModifiyUser'
export const USER_MENU_USER_GROUP = '/User-menu-UserGroup'
export const SALES_MENU_CATEGORY_ADD = '/Sales-menu-CategoryAdd'
  